Sprint №9
mikhaylenko-sd/java-filmorate pull request #1
Opened 2022-11-25 14:34 UTC by mikhaylenko-sd

-Created new Spring Boot Application"Filmorate"

2022-11-26 14:38 UTC, Fleaman777 requested changes

2022-11-26 14:38 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final HashMap<Integer, Film> films = new HashMap<>();
тип перемнной лучше делать более широкий Map, так полиморфизм будет отрабтывать в полной мере: будет меньше проблем, если нужно будет поменять реализацию места хрананения на другую мапу

2022-11-26 14:38 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/GeneratorId.java
> +public class GeneratorId {
интересный подход с реализацией генератора id в виде отдельного класса

2022-11-26 14:38 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void filmValidate(Film film) {
молодец, что валидацию вынесла в отдельный метод, так более грамотно, 
+здорово, что у каждой ошибки свое собственное сообщение

2022-11-26 14:38 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final HashMap<Integer, User> users = new HashMap<>();
здсь аналагично как и в FilmController

2022-11-26 14:38 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        }
Вот этот if-else тоже можно было бы вынести в отдельный метод, 
тем самым немного разделив ответсвенность выполнения в методе create

аналагично и в UserController

2022-11-26 14:38 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Long duration;
поля должны быть private

2022-11-26 14:38 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +}
и здесь тоже private

2022-11-26 14:38 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        Film film4 = new Film(0, "Аватар4", "Фильм про синих людей, часть 4", LocalDate.of(2022, Month.NOVEMBER, 1), (long) 180);
что бы не дублировать создание тестовых фильмов в каждом тесте, общие можно вынести в константы, или создание этих фильмов в метод с аннотацией @BeforeEach 

аналагично в тестах для юзера

2022-11-26 14:38 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private void userValidate(User user) {
метод должен начинаться с глагола, т.е validateUser

2022-11-26 14:38 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        }
чуть более правильный подход тогда, когда контроллер только принимает запросы и отдает респонсы, а всю остальную логику выполняют другие классы(сервисы)

это не считается сейчас ошибкой,
выносить этот метод в отдельный класс или нет остается за тобой :)

аналагично и в юзер контроллере

2022-11-26 14:38 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +}
В enterprise приложениях на java, особенно написанных на Spring, в ....ControllerTest обычно тестируется api - на контроллер приходят определенные запросы(это делается специальной сущностью(MockMvc), а не просто вызывается эндпоинт метод), приложение полностью все отрабатывает, и затем отвечает определенным кодом и response body, которые и проверяются - такие тесты называются интеграционными. им ты научишься чуть позже

Валидацию хорошо тестировать в обычных юнит тестах. Как раз, это будет проще сделать, если ее вынести в отдельный класс в отдельной директории.

этот комментарий тоже больше для информации,
если вдруг решишь часть валидации вынести в отдельный класс, можешь частично реализовать этот подход

2022-11-26 23:37 UTC, mikhaylenko-sd commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +}
Спасибо за замечание, я это учту в дальнейшем, но сейчас пока оставлю так.

2022-11-27 10:11 UTC, Fleaman777 approved these changes

2022-11-27 10:11 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +public class FilmServiceImpl implements FilmService {
оочень круто, 

Молодец, что решила сразу создать интерфейс сервиса и его имплементацию, 
такой подход, безусловно, грамотней

2022-12-06 16:40 UTC, merged