sprint №10
mikhaylenko-sd/java-filmorate pull request #2
Opened 2022-12-09 00:11 UTC by mikhaylenko-sd

The project updated in accordance with the technical specification from Sprint №10.

2022-12-09 15:22 UTC, Fleaman777 requested changes

2022-12-09 15:22 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmService.class);
у ломбок библиотеки есть отличная аннотация @Slf4j, 
можно использовать ее вместо явного объявления логгера в классе

2022-12-09 15:22 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (id <= 0 || userId <= 0) {
что бы не дублировать общую валидацию в разных методах,
 ее можно было бы вынести в отдельные вспомогательные методы,

2022-12-09 15:22 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        }
а вот здесь молодец, что вынесла валидацию в отдельный метод, это правильный подход

2022-12-09 15:22 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserServiceTest.java
> +    }
отличный метод с аннотацией @BeforeEach вкдючает в себя все небходимое перед запуском тестов

2022-12-09 21:27 UTC, mikhaylenko-sd commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (id <= 0 || userId <= 0) {
спасибо, вынесла, но названия какие-то неудачные получились, если есть идеи как получше написать, то они принимаются)))

2022-12-10 15:49 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (id <= 0 || userId <= 0) {
на самом деле хорошо названы, 
основные моменты учтены: если метод возвращает boolean, для лучшего восприятия, он должен начинаться с is или are. 
валидационные void методы, начинаются с validate

2022-12-11 22:31 UTC, merged