sprint №11
mikhaylenko-sd/java-filmorate pull request #4
Opened 2023-01-07 21:46 UTC by mikhaylenko-sd

added DB logic

2023-01-09 09:07 UTC, Fleaman777 requested changes

2023-01-09 09:07 UTC, Fleaman777 commented on pom.xml
> +			<artifactId>spring-boot-starter-data-jpa</artifactId>
хорошая зависимость, и она позже будет использоваться, 
но на данном этапе она слегка избыточна, т.к в ней находится много лишних вещей 
так что пока лучше использовть  org.springframework.boot.spring-boot-starter-data-jdbc

2023-01-09 09:07 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        }
этот foreach можно было бы написать чуть компактней: 
films.foreach(this::fillLikesAndGenres);

2023-01-09 09:07 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +    private void fillLikesAndGenres(Film film) {
вспомогательные методы должны идти после публичных, 
так при беглом взгляде на класс, можно будет быстро понять, какой фукционал этот класс отдает наружу

2023-01-09 09:07 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +            throw new FilmNotFoundException(id);
хороший варианта обработки else - проброс исключения

2023-01-09 09:07 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                    .findAny().orElse(null);
у Optional есть метод orElseThrow - можно попробовать использовать его, что бы не возвращать null и не проверять его через if-else

2023-01-09 09:07 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryUserStorage.java
> +    }
хороший подход, общая часть вынесена в отдельный метод

2023-01-09 09:07 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +                    .findAny().orElse(null);
здесть тоже можно было бы попробовать применить orElseThrow 

аналогично в похожих местах

2023-01-09 09:07 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageTest.java
> +    void getById() {
лучше тест методы называть немного по другому, чем оригиналы, 
так, если что, будет проще искать оригинальный метод по всему приложению

самое простое другое название, добавить слово test, еще лучше, указать. при каких условиях он выполнен, 
например
testGetByIdIf.....

2023-01-09 09:11 UTC, Fleaman777 requested changes

2023-01-09 09:11 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryUserStorage.java
>  public class InMemoryUserStorage implements UserStorage {
можно этот класс и FIlm... вынести в отдельный пекедж, что бы было чуть удобней ориентироваться в классах

2023-01-10 18:27 UTC, Fleaman777 approved these changes

2023-01-11 09:46 UTC, mikhaylenko-sd commented
Схема БД в файл README была добавлена в промежуточном 11 спринте и влита в ветку **main**

2023-01-12 15:43 UTC, merged